config/routes.rb
Rails.application.routes.draw do

  resources :characters do
    resources :helpers
    resources :items
  end
  devise_for :users
  root 'characters#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  def generate_filename
    value = false
    randomFileName = rand 100000000000000000000000000000000000000000
    randomFileName = randomFileName.to_s + ".img"
    Character.all.each do |i| value = true if i.image == randomFileName end
    if value
      generate_filename
    else
      return randomFileName
    end
  end
  
  validates :name, presence: true
  validates :str, presence: true, numericality: {:greater_than => 0}
  validates :dex, presence: true, numericality: {:greater_than => 0}
  validates :spd, presence: true, numericality: {:greater_than => 0}
  validates :con, presence: true, numericality: {:greater_than => 0}
  validates :end, presence: true, numericality: {:greater_than => 0}
  validates :min, presence: true, numericality: {:greater_than => 0}
  validates :sol, presence: true, numericality: {:greater_than => 0}

  has_many :items
  belongs_to :user
end

app/models/helper.rb
class Helper < ActiveRecord::Base
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :character
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :helpers
  has_many :characters
 # has_many :items :through :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @characters = Character.all
    respond_with(@characters)
  end

  def show
    respond_with(@character)
  end

  def new
    @character = Character.new
    @edit = false
    respond_with(@character)
  end

  def edit
    @edit = true if @character.errors.any?
  end

  def create
    @character = Character.new(character_params)
    @character.image = @character.generate_filename
    if params[:character][:uploaded_file]
      @uploaded_io = params[:character][:uploaded_file]
      File.open(Rails.root.join('public', 'images', @character.image), 'wb') do |file|
        file.write(@uploaded_io.read)
      end
    else
      @character.image = 'default.png'
    end

    @character.lv = 1
    @character.exp = 0
    @character.user_id = current_user.id

=begin
    @character.con = 1 if !@character.con
    @character.min = 1 if !@character.min
    @character.end = 1 if !@character.end
=end

    @character.hp = @character.con * 10 if @character.con
    @character.mp = @character.min * 10 if @character.min
    @character.ep = @character.end * 10 if @character.end

=begin
    @character.sol = 1 if !@character.sol
    @character.str = 1 if !@character.str
    @character.dex = 1 if !@character.dex
    @character.spd = 1 if !@character.spd
=end
    total = 0
    total = (@character.str + @character. dex + @character.spd + @character.con + @character.end + @character.min + @character.sol) if checkValid
    if total <= 20 
      @character.save
      respond_with @character

    else
      @myMessage = "Your values added up to " + total.to_s + " Please use less points."
      render :new
    end
  end

  def update
    @character.update(character_params)
    respond_with(@character)
  end

  def destroy
    @character.destroy
    respond_with(@character)
  end

  def checkValid
    return false if @character.str
    return false if @character.dex
    return false if @character.spd
    return false if @character.end
    return false if @character.con
    return false if @character.min
    return false if @character.sol

  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      params.require(:character).permit(:name, :user_id, :hp, :mp, :ep, :str, :dex, :spd, :con, :end, :min, :sol, :lv, :exp)
    end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @helpers = Helper.all
    respond_with(@helpers)
  end

  def show
    respond_with(@helper)
  end

  def new
    @helper = Helper.new
    respond_with(@helper)
  end

  def edit
  end

  def create
    @helper = Helper.new(helper_params)
    @helper.save
    respond_with(@helper)
  end

  def update
    @helper.update(helper_params)
    respond_with(@helper)
  end

  def destroy
    @helper.destroy
    respond_with(@helper)
  end

  private
    def set_helper
      @helper = Helper.find(params[:id])
    end

    def helper_params
      params.require(:helper).permit(:name, :user_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @character = Character.find(params[:character_id])
    @item = Item.new
    @randItem = randItem
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to root_path
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  def randItem
    list = ["form_sword", "form_fullplate", "form_diamond", "form_card", "form_toys"]
    return list.sample
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.permit(:name, :kind, :att, :def, :worth, :character_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/characters/_form.html.erb
<%= form_for @character, :html => { :class => "form-horizontal character" } do |f| %>

    <% if @character.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @character.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:name]) %>
  </div>
<% if @edit == false  %>
  <div class="control-group">
    <%= f.label :str, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :str, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:str]) %>
  </div>
  <div class="control-group">
    <%= f.label :dex, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dex, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:dex]) %>
  </div>
  <div class="control-group">
    <%= f.label :spd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :spd, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:spd]) %>
  </div>
  <div class="control-group">
    <%= f.label :con, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :con, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:con]) %>
  </div>
  <div class="control-group">
    <%= f.label :end, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:end]) %>
  </div>
  <div class="control-group">
    <%= f.label :min, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :min, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:min]) %>
  </div>
  <div class="control-group">
    <%= f.label :sol, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sol, :class => 'form-control' %>
    </div>
    <%= error_span(@character[:sol]) %>
  </div>

  <% end %>
</div>
  <div class="control-group">
    <strong><p>Please choose an avatar for you character. If left blank a default image will be used </p></strong>
    <div class="controls">
      <%= f.file_field :uploaded_file, :class => 'btn-default'%>
    </div>
  </div>
<br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            characters_path, :class => 'btn btn-default' %>

<% end %>

app/views/characters/edit.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/index.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:hp) %></th>
      <th><%= model_class.human_attribute_name(:mp) %></th>
      <th><%= model_class.human_attribute_name(:ep) %></th>
      <th><%= model_class.human_attribute_name(:str) %></th>
      <th><%= model_class.human_attribute_name(:dex) %></th>
      <th><%= model_class.human_attribute_name(:spd) %></th>
      <th><%= model_class.human_attribute_name(:con) %></th>
      <th><%= model_class.human_attribute_name(:end) %></th>
      <th><%= model_class.human_attribute_name(:min) %></th>
      <th><%= model_class.human_attribute_name(:sol) %></th>
      <th><%= model_class.human_attribute_name(:lv) %></th>
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <% if character.user == current_user %>
        <tr>
        <td><%= link_to character.name, character_path(character) %></td>
        <td><%= character.hp %></td>
        <td><%= character.mp %></td>
        <td><%= character.ep %></td>
        <td><%= character.str %></td>
        <td><%= character.dex %></td>
        <td><%= character.spd %></td>
        <td><%= character.con %></td>
        <td><%= character.end %></td>
        <td><%= character.min %></td>
        <td><%= character.sol %></td>
        <td><%= character.lv %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_character_path(character), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      character_path(character),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_character_path,
            :class => 'btn btn-primary' %>

app/views/characters/new.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<br>
<strong><p>Please set your stats. You total must add up to 20 points and you must have at least a value of 1 in each stat.</p></strong>
<br>
<p><%= @myMessage if @myMessage%></p>
<p><%= @error if @error %> </p>
<br>

<%= render :partial => 'form' %>

app/views/helpers/_form.html.erb
<%= form_for(@helper) do |f| %>
  <% if @helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@helper.errors.count, "error") %> prohibited this helper from being saved:</h2>

      <ul>
      <% @helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helpers/edit.html.erb
<h1>Editing helper</h1>

<%= render 'form' %>

<%= link_to 'Show', @helper %> |
<%= link_to 'Back', helpers_path %>

app/views/helpers/index.html.erb
<h1>Listing helpers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helpers.each do |helper| %>
      <tr>
        <td><%= helper.name %></td>
        <td><%= helper.user %></td>
        <td><%= link_to 'Show', helper %></td>
        <td><%= link_to 'Edit', edit_helper_path(helper) %></td>
        <td><%= link_to 'Destroy', helper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Helper', new_helper_path %>

app/views/helpers/new.html.erb
<h1>New helper</h1>

<%= render 'form' %>

<%= link_to 'Back', helpers_path %>

app/views/helpers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @helper.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @helper.user %>
</p>

<%= link_to 'Edit', edit_helper_path(@helper) %> |
<%= link_to 'Back', helpers_path %>

app/views/items/_form.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :att %><br>
    <%= f.number_field :att %>
  </div>
  <div class="field">
    <%= f.label :def %><br>
    <%= f.number_field :def %>
  </div>
  <div class="field">
    <%= f.label :worth %><br>
    <%= f.number_field :worth %>
  </div>
  <div class="field">
    <%= f.label :character_id %><br>
    <%= f.text_field :character_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_form_card.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <p>Deck of Many Things</p>
      <%= hidden_field_tag :name, 'Deck of Many Things' %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <p>Treasure</p>
      <%= hidden_field_tag :kind, 'Treasure' %>
    </div>
    <div class="field">
      <%= f.label :att %><br>
      <p>0</p>
      <%= hidden_field_tag :att, '0' %>
    </div>
    <div class="field">
      <%= f.label :def %><br>
      <p>0</p>
      <%= hidden_field_tag :def, '0' %>
    </div>
    <div class="field">
      <%= f.label :worth %><br>
      <p>500</p>
      <%= hidden_field_tag :worth, '500' %>
    </div>
    <div class="field">
      <%= hidden_field_tag :character_id,  @character.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_form_diamond.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <p>Diamond</p>
      <%= hidden_field_tag :name, 'Diamond' %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <p>Treasure</p>
      <%= hidden_field_tag :kind, 'Treasure' %>
    </div>
    <div class="field">
      <%= f.label :att %><br>
      <p>0</p>
      <%= hidden_field_tag :att, '0' %>
    </div>
    <div class="field">
      <%= f.label :def %><br>
      <p>0</p>
      <%= hidden_field_tag :def, '0' %>
    </div>
    <div class="field">
      <%= f.label :worth %><br>
      <p>5000</p>
      <%= hidden_field_tag :worth, '5000' %>
    </div>
    <div class="field">
      <%= hidden_field_tag :character_id,  @character.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_form_fullplate.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <p>FullPlate</p>
      <%= hidden_field_tag :name, 'FullPlate' %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <p>Armor</p>
      <%= hidden_field_tag :kind, 'Armor' %>
    </div>
    <div class="field">
      <%= f.label :att %><br>
      <p>0</p>
      <%= hidden_field_tag :att, '0' %>
    </div>
    <div class="field">
      <%= f.label :def %><br>
      <p>5</p>
      <%= hidden_field_tag :def, '5' %>
    </div>
    <div class="field">
      <%= f.label :worth %><br>
      <p>100</p>
      <%= hidden_field_tag :worth, '100' %>
    </div>
    <div class="field">
      <%= hidden_field_tag :character_id,  @character.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_form_sword.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <p>Sword</p>
      <%= hidden_field_tag :name, 'Sword' %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <p>Weapon</p>
      <%= hidden_field_tag :kind, 'Weapon' %>
    </div>
    <div class="field">
      <%= f.label :att %><br>
      <p>3</p>
      <%= hidden_field_tag :att, '3' %>
    </div>
    <div class="field">
      <%= f.label :def %><br>
      <p>0</p>
      <%= hidden_field_tag :def, '0' %>
    </div>
    <div class="field">
      <%= f.label :worth %><br>
      <p>5</p>
      <%= hidden_field_tag :worth, '5' %>
    </div>
    <div class="field">
      <%= hidden_field_tag :character_id,  @character.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_form_toys.html.erb
<%= form_for([@character, @item], :html => { :class => "form-horizontal character" }) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <p>Children Toy's</p>
      <%= hidden_field_tag :name, 'Children Toys' %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <p>Treasure</p>
      <%= hidden_field_tag :kind, 'Treasure' %>
    </div>
    <div class="field">
      <%= f.label :att %><br>
      <p>0</p>
      <%= hidden_field_tag :att, '0' %>
    </div>
    <div class="field">
      <%= f.label :def %><br>
      <p>0</p>
      <%= hidden_field_tag :def, '0' %>
    </div>
    <div class="field">
      <%= f.label :worth %><br>
      <p>1</p>
      <%= hidden_field_tag :worth, '1' %>
    </div>
    <div class="field">
      <%= hidden_field_tag :character_id,  @character.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Att</th>
      <th>Def</th>
      <th>Worth</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.type %></td>
        <td><%= item.att %></td>
        <td><%= item.def %></td>
        <td><%= item.worth %></td>
        <td><%= item.character %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>Got item</h1>

<%= render @randItem %>

<%= link_to 'Back', character_path(@character.id) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @item.type %>
</p>

<p>
  <strong>Att:</strong>
  <%= @item.att %>
</p>

<p>
  <strong>Def:</strong>
  <%= @item.def %>
</p>

<p>
  <strong>Worth:</strong>
  <%= @item.worth %>
</p>

<p>
  <strong>Character:</strong>
  <%= @item.character %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trpg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<link href="mystyle.css" rel="stylesheet" type="text/css" id="styleType">-->
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.js"></script>
  <%= javascript_include_tag "application" %>
</head>
<body ng-app='MyApp' style="background-color: lightblue">
<div id="user_nav">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or
<%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>
<%= yield %>

</body>
</html>